Repository epam/edp-keycloak-operator, pull requests merged in 2024-11, with the labels that each got.

#108 fix: Boolean parameters with default values are always 'true'
  api/common/realm.go
  api/v1/keycloakclient_types.go
  api/v1/keycloakrealmuser_types.go
Labels: bug

#110 feat: Add print columns for KeycloakRealm Resources
  api/v1/keycloakrealm_types.go
  api/v1alpha1/clusterkeycloakrealm_types.go
  config/crd/bases/v1.edp.epam.com_clusterkeycloakrealms.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml
  deploy-templates/crds/v1.edp.epam.com_clusterkeycloakrealms.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
Labels: enhancement

#111 feat: Add the ability to manage Realm Attributes
  .golangci.yaml
  Makefile
  api/common/realm.go
  api/common/ref.go
  api/common/zz_generated.deepcopy.go
  api/v1/keycloakrealm_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/clusterkeycloakrealm_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/v1.edp.epam.com_clusterkeycloakrealms.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml
  config/samples/v1_v1_keycloakrealm.yaml
  controllers/clusterkeycloakrealm/chain/auth_flow_test.go
  controllers/clusterkeycloakrealm/chain/factory.go
  controllers/clusterkeycloakrealm/chain/user_profile.go
  controllers/clusterkeycloakrealm/chain/user_profile_test.go
  controllers/helper/controller_helper_auth_test.go
  controllers/keycloakclient/chain/process_permissions_test.go
  controllers/keycloakclient/chain/process_policy_test.go
  controllers/keycloakclient/chain/process_resources_test.go
  controllers/keycloakclient/chain/process_scope_test.go
  controllers/keycloakclient/chain/put_client_scope_test.go
  controllers/keycloakclient/chain/put_client_test.go
  controllers/keycloakclient/keycloakclient_controller.go
  controllers/keycloakrealm/chain/factory.go
  controllers/keycloakrealm/chain/user_profile.go
  controllers/keycloakrealm/chain/user_profile_test.go
  controllers/keycloakrealm/keycloakrealm_controller_integration_test.go
  controllers/keycloakrealmgroup/keycloakrealmgroup_controller.go
  controllers/keycloakrealmidentityprovider/keycloakrealmidentityprovider_controller.go
  controllers/keycloakrealmrolebatch/keycloakrealmrolebatch_controller.go
  deploy-templates/_crd_examples/keycloakrealm.yaml
  deploy-templates/crds/v1.edp.epam.com_clusterkeycloakrealms.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/client/keycloak/adapter/errors_test.go
  pkg/client/keycloak/adapter/gocloak_adapter.go
  pkg/client/keycloak/adapter/gocloak_adapter_client_scope_test.go
  pkg/client/keycloak/adapter/gocloak_adapter_client_test.go
  pkg/client/keycloak/adapter/gocloak_adapter_groups.go
  pkg/client/keycloak/adapter/gocloak_adapter_groups_test.go
  pkg/client/keycloak/adapter/gocloak_adapter_realms_test.go
  pkg/client/keycloak/adapter/gocloak_adapter_roles_test.go
  pkg/client/keycloak/adapter/gocloak_adapter_test.go
  pkg/client/keycloak/adapter/gocloak_adapter_user.go
  pkg/client/keycloak/adapter/gocloak_adapter_user_test.go
  pkg/client/keycloak/adapter/mocks/gocloak_mock.go
  pkg/client/keycloak/dto/keycloak_dto.go
  pkg/client/keycloak/keycloak_client.go
  pkg/client/keycloak/mocks/client_mock.go
  pkg/fakehttp/server_test.go
  pkg/objectmeta/deletion_test.go
  pkg/secretref/secretref_test.go
Labels: feature

#112 feat: Add setting adminUrl homeUrl for Client
  api/v1/keycloakclient_types.go
  config/crd/bases/v1.edp.epam.com_keycloakclients.yaml
  controllers/keycloakclient/keycloakclient_controller_integration_test.go
  deploy-templates/_crd_examples/keycloakclient.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakclients.yaml
  docs/api.md
  pkg/client/keycloak/adapter/gocloak_adapter.go
  pkg/client/keycloak/dto/keycloak_dto.go
Labels: feature

#104 chore: Update current development version (#102)
  README.md
  bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml
  deploy-templates/README.md
  deploy-templates/README.md.gotmpl
Labels: enhancement
