Repository epam/edp-keycloak-operator, pull requests merged in 2024-07, with the labels that each got.

#74 bug: move imagePullSecrets to spec.template.spec
  deploy-templates/templates/deployment.yaml
Labels: bug

#77 chore: Update current development version (#76)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#78 chore: Add additional examples of Keycloak AuthFlow resource
  deploy-templates/_crd_examples/keycloakauthflow.yaml
Labels: documentation

#81 feat: Add displayHTMLName to realm resource
  api/v1/keycloakrealm_types.go
  config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml
  controllers/keycloakrealm/chain/realm_settings.go
  controllers/keycloakrealm/chain/realm_settings_test.go
  deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
  docs/api.md
  pkg/client/keycloak/adapter/gocloak_adapter_realms.go
Labels: enhancement

#87 feat: Remove deprecated v1alpha1 versions from the operator
  api/v1alpha1/clusterkeycloak_types.go
  api/v1alpha1/clusterkeycloakrealm_types.go
  api/v1alpha1/keycloak_types.go
  api/v1alpha1/keycloak_types_test.go
  api/v1alpha1/keycloakauthflow_types.go
  api/v1alpha1/keycloakclient_types.go
  api/v1alpha1/keycloakclientscope_types.go
  api/v1alpha1/keycloakcomponent_types.go
  api/v1alpha1/keycloakrealm_types.go
  api/v1alpha1/keycloakrealmgroup_types.go
  api/v1alpha1/keycloakrealmidentityprovider_types.go
  api/v1alpha1/keycloakrealmrole_types.go
  api/v1alpha1/keycloakrealmrolebatch_types.go
  api/v1alpha1/keycloakrealmuser_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml
  bundle/manifests/v1.edp.epam.com_keycloakauthflows.yaml
  bundle/manifests/v1.edp.epam.com_keycloakclients.yaml
  bundle/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealms.yaml
  bundle/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
  bundle/manifests/v1.edp.epam.com_keycloaks.yaml
  config/crd/bases/v1.edp.epam.com_keycloakauthflows.yaml
  config/crd/bases/v1.edp.epam.com_keycloakclients.yaml
  config/crd/bases/v1.edp.epam.com_keycloakclientscopes.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealmcomponents.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealmgroups.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealmrolebatches.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealmroles.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml
  config/crd/bases/v1.edp.epam.com_keycloakrealmusers.yaml
  config/crd/bases/v1.edp.epam.com_keycloaks.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakauthflows.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakclients.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakclientscopes.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealmcomponents.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealmgroups.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealmrolebatches.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealmroles.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloakrealmusers.yaml
  deploy-templates/crds/v1.edp.epam.com_keycloaks.yaml
  docs/api.md
Labels: enhancement
